version: '3.9'
services:
  s_webserver:
    container_name: c_web_server
    build: 
      context: ./nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./Projects:/var/www/html/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - s_php8
      - s_php74
  s_nvm:
    container_name: c_nvm
    build:
      context: ./nvm
    volumes:
      - ./Projects:/var/www/html/
    restart: on-failure
    command: ["sleep","infinity"]
  s_php8:
    container_name: c_php8
    build:
      context: ./php8
    restart: always
    hostname: php8 
    ports:
      - "9000:9000"
    volumes:
      - ./Projects:/var/www/html/
      - ./php8/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php8/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - s_mysql
  s_php74:
    container_name: c_php74
    build:
      context: ./php74
    restart: always
    hostname: php74 
    ports:
      - "8000:9000"
    volumes:
      - ./Projects:/var/www/html/
      - ./php74/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php74/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - s_mysql
  s_mysql:
    container_name: c_mysql
    env_file:
      - ./database/mysql/.env
    restart: always
    build:
      context: ./database/mysql
    hostname: mysql
    ports:
      - 3308:3306
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:

